# Generated by Django 5.2.9 on 2025-12-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('ADMIN', 'admin')], max_length=10),
        ),
    ]
